import type { BoardSection } from "@/components/post-board"

const FOLDER = "/images/photography/AQUI/"

export const aquiBoard: BoardSection[] = [
  {
    id: "clockwork",
    title: "Clockwork",
    note: "",
    columns: 12,
    rowHeight: 30,
    gap: 16,
    items: [
      // big anchor photo, top-left
      {
        id: "aqui-01",
        src: `${FOLDER}20221013-180609-006.jpg`,
        alt: " ",
        colStart: 1,
        colSpan: 5,
        rowStart: 1,
        rowSpan: 12,
        rotate: -2,
        pin: "tape",
      },
      // title chip, black block like "THE DARK SIDE"
      {
        kind: "label",
        id: "title",
        text: "",
        size: "xl",
        tone: "dark",
        colStart: 6,
        colSpan: 4,
        rowStart: 1,
        rowSpan: 3,
        rotate: 0,
      },
      {
        id: "aqui-02",
        src: `${FOLDER}20221029-182310.jpg`,
        alt: "",
        colStart: 6,
        colSpan: 4,
        rowStart: 4,
        rowSpan: 9,
        rotate: 2,
        pin: "pin",
      },
      // vertical word label, like "Gothic" in the reference
      {
        kind: "label",
        id: "tag-film",
        text: "",
        size: "lg",
        tone: "dark",
        orientation: "vertical",
        colStart: 10,
        colSpan: 1,
        rowStart: 1,
        rowSpan: 12,
      },
      {
        id: "aqui-03",
        src: `${FOLDER}20221116-161023-15.jpg`,
        alt: "",
        caption: "",
        captionPlacement: "overlay-bottom",
        captionSize: "sm",
        colStart: 11,
        colSpan: 2,
        rowStart: 1,
        rowSpan: 12,
        rotate: -1,
        pin: "clip",
      },
      // small tag chip, like "Lace" / "Dark" one-word labels
      {
        kind: "label",
        id: "tag-slow",
        text: "Slow",
        size: "sm",
        tone: "light",
        colStart: 1,
        colSpan: 2,
        rowStart: 13,
        rowSpan: 2,
      },
      {
        id: "aqui-04",
        src: `${FOLDER}20221213-165734-84.jpg`,
        alt: "",
        caption: "",
        captionPlacement: "right",
        captionSize: "sm",
        colStart: 3,
        colSpan: 4,
        rowStart: 13,
        rowSpan: 8,
        rotate: 1,
        pin: "tape",
      },
      {
        id: "aqui-05",
        src: `${FOLDER}20230126-134049-13.jpg`,
        alt: "",
        caption: "",
        captionPlacement: "below",
        captionSize: "sm",
        colStart: 7,
        colSpan: 3,
        rowStart: 13,
        rowSpan: 9,
        rotate: -2,
        pin: "pin",
      },
      {
        id: "aqui-06",
        src: `${FOLDER}20230620-195453-06.jpg`,
        alt: "",
        caption: "",
        captionPlacement: "overlay-top",
        captionSize: "sm",
        colStart: 10,
        colSpan: 3,
        rowStart: 13,
        rowSpan: 9,
        rotate: 3,
        pin: "clip",
      },
    ],
  },
]