import type { BoardSection } from "@/components/post-board"

const FOLDER = "/images/photography/AQUI/"

export const aquiBoard: BoardSection[] = [
  {
    id: "clockwork",
    title: "Clockwork",
    note: "One roll of film, shot over a year at the same café.",
    columns: 12,
    gap: 20,
    items: [
      {
        kind: "label",
        id: "title",
        text: "AQUI",
        size: "xl",
        tone: "dark",
        colStart: 1,
        colSpan: 3,
        rowStart: 1,
        rotate: -1,
      },
      {
        id: "aqui-01",
        src: `${FOLDER}20221013-180609-006.jpg`,
        alt: "Morning counter light",
        aspectRatio: "4 / 5",
        colStart: 1,
        colSpan: 3,
        rowStart: 2,
        rotate: -2,
        pin: "tape",
        caption: "The espresso machine hisses awake before the first order.",
        captionPlacement: "below",
      },
      {
        id: "aqui-02",
        src: `${FOLDER}20221029-182310.jpg`,
        alt: "Light through the window",
        aspectRatio: "3 / 4",
        colStart: 4,
        colSpan: 4,
        rowStart: 1,
        rotate: 2,
        pin: "pin",
      },
      {
        kind: "label",
        id: "tag-film",
        text: "Film",
        size: "lg",
        tone: "dark",
        orientation: "vertical",
        colStart: 8,
        colSpan: 1,
        rowStart: 1,
      },
      {
        id: "aqui-03",
        src: `${FOLDER}20221116-161023-15.jpg`,
        alt: "Notebook and cup on the table",
        aspectRatio: "5 / 4",
        colStart: 9,
        colSpan: 4,
        rowStart: 1,
        rotate: -1,
        pin: "clip",
        caption: "Someone always leaves a book open on this table.",
        captionPlacement: "overlay-bottom",
      },
      {
        id: "aqui-04",
        src: `${FOLDER}20221213-165734-84.jpg`,
        alt: "Vinyl corner",
        aspectRatio: "1 / 1",
        colStart: 4,
        colSpan: 3,
        rowStart: 6,
        rotate: 1,
        pin: "tape",
        caption: "The turntable skips on track two. Nobody minds.",
        captionPlacement: "right",
      },
      {
        kind: "palette",
        id: "palette",
        colors: ["#EFE7DA", "#B9AFA0", "#3A3733", "#C9B79C"],
        label: "AQUI tones",
        colStart: 7,
        colSpan: 2,
        rowStart: 7,
      },
      {
        id: "aqui-05",
        src: `${FOLDER}20230126-134049-13.jpg`,
        alt: "Winter light on the wall",
        aspectRatio: "4 / 5",
        colStart: 9,
        colSpan: 4,
        rowStart: 6,
        rotate: -2,
        pin: "pin",
        caption: "January light barely clears the rooftops.",
        captionPlacement: "below",
      },
      {
        id: "aqui-06",
        src: `${FOLDER}20230620-195453-06.jpg`,
        alt: "Summer evening at the counter",
        aspectRatio: "16 / 10",
        colStart: 1,
        colSpan: 6,
        rowStart: 10,
        rotate: 1,
        pin: "clip",
        caption: "Last order, six-thirty, the light still hasn't given up.",
        captionPlacement: "overlay-top",
      },
    ],
  },
]