import type { BoardSection } from "@/components/post-board"

const FOLDER = "/images/photography/AQUI/"

export const aquiBoard: BoardSection[] = [
  {
    id: "morning",
    title: "Morning Light",
    note: "First hour after opening — steam, quiet counters, low sun through the window.",
    columns: 12,
    rowHeight: 32,
    gap: 20,
    items: [
      {
        id: "aqui-01",
        src: `${FOLDER}20221013-180609-006.jpg`,
        alt: "Morning counter at AQUI",
        caption: "The espresso machine hisses awake before the first customer walks in.",
        captionPlacement: "below",
        captionSize: "sm",
        colStart: 1,
        colSpan: 5,
        rowStart: 1,
        rowSpan: 8,
        rotate: -3,
        pin: "tape",
      },
      {
        id: "aqui-02",
        src: `${FOLDER}20221029-182310.jpg`,
        alt: "Light through the window",
        captionPlacement: "none",
        colStart: 6,
        colSpan: 4,
        rowStart: 2,
        rowSpan: 6,
        rotate: 2,
        pin: "pin",
      },
      {
        id: "aqui-03",
        src: `${FOLDER}20221116-161023-15.jpg`,
        alt: "Notebook and cup",
        caption: "Someone always leaves a book open on this table.",
        captionPlacement: "overlay-bottom",
        captionSize: "md",
        colStart: 10,
        colSpan: 3,
        rowStart: 1,
        rowSpan: 9,
        rotate: -1,
        pin: "clip",
      },
    ],
  },
  {
    id: "afternoon",
    title: "Slow Afternoon",
    note: "Regulars, the same three seats, and whatever's playing on vinyl.",
    columns: 12,
    rowHeight: 32,
    gap: 20,
    items: [
      {
        id: "aqui-04",
        src: `${FOLDER}20221213-165734-84.jpg`,
        alt: "Vinyl corner",
        caption: "The turntable skips on track two. Nobody minds.",
        captionPlacement: "right",
        captionSize: "sm",
        colStart: 1,
        colSpan: 6,
        rowStart: 1,
        rowSpan: 7,
        rotate: 1,
        pin: "tape",
      },
      {
        id: "aqui-05",
        src: `${FOLDER}20230126-134049-13.jpg`,
        alt: "Winter light on the wall",
        caption: "January light barely clears the rooftops across the street.",
        captionPlacement: "below",
        captionSize: "sm",
        colStart: 8,
        colSpan: 5,
        rowStart: 2,
        rowSpan: 6,
        rotate: -2,
        pin: "pin",
      },
      {
        id: "aqui-06",
        src: `${FOLDER}20230620-195453-06.jpg`,
        alt: "Summer evening",
        caption: "Last order, six-thirty, the light still hasn't given up.",
        captionPlacement: "overlay-top",
        captionSize: "sm",
        colStart: 2,
        colSpan: 4,
        rowStart: 8,
        rowSpan: 6,
        rotate: 3,
        pin: "clip",
      },
    ],
  },
]